# These are supported funding model platforms

github: [javthon]
patreon: javthon
open_collective: javthon
ko_fi: javthon
tidelift: maven/io.github.javthon.mybatis-generator-yml-maven-plugin
community_bridge: mybatis-generator-yml-maven-plugin
liberapay: javthon
issuehunt: javthon
otechie: javthon
custom: [https://paypal.me/xxf666]
