mybatisGenerator:
    datasource:
        url: jdbc:mysql://35.234.41.130:3306/JS_mysql_db
        username: root
        password: Woshixxf666

    targetPackage:
        model: com.example.domain
        javaMapper: com.example.dao
        xmlMapper: com.example.dao

    mapperConfig:
        comment: false
        lombok: true
        swagger: true
        #MyBatis3DynamicSql, MyBatis3Simple, MyBatis3
        targetRuntime: MyBatis3
        #mapper, dao or other
        mapperSuffixName: dao

#        enableCountByExample: false
#        enableUpdateByExample: false
#        enableDeleteByExample: false
#        enableSelectByExample: false
#        selectByExampleQueryId: false

    tables:
        - fence



