mybatisGenerator:
    datasource:
        url: jdbc:mysql://35.234.41.130:3306/JS_mysql_db
        username: root
        password: Woshixxf666

    targetPackage:
        model: com.example.domain
        javaMapper: com.example.dao
        xmlMapper: com.example.dao

    mapperConfig:
        comment: true
        lombok: true
        swagger: false

        mapperSuffixName: dao
        mode: mybatis3

        enableCountByExample: false
        enableUpdateByExample: true
        enableDeleteByExample: false
        enableSelectByExample: true
        selectByExampleQueryId: false

    tables:
        - fence



