mybatisGenerator:
    datasource:
        url: jdbc:mysql://35.234.41.130:3306/JS_mysql_db
        username: root
        password: Woshixxf666

    targetPackage:
        model: com.example.domain
        javaMapper: com.example.dao
        xmlMapper: com.example.dao

    #MyBatis3DynamicSql, MyBatis3Simple, MyBatis3
    targetRuntime: MyBatis3Simple
    #mapper, dao or other
    mapperSuffixName: dao
    java8: true

    plugins:
        comment: false
        lombok: false
        swagger: true

    tables:
        - fence



