mybatisGenerator:
    datasource:
        url: jdbc:mysql://35.234.41.130:3306/JS_mysql_db
        username: root
        password: Woshixxf666

    targetPackage:
        model: com.example.domain
        javaMapper: com.example.dao
        xmlMapper: com.example.dao

    #MyBatis3DynamicSql, MyBatis3, MyBatis3Simple
    targetRuntime: MyBatis3
    #mapper, dao or other
    mapperSuffixName: mapper
    java8: false
    disableExample: true

    plugins:
        comment: true
        lombok: true
        swagger: false
        mapperAnnotation: true
        serializable: true

    tables:
        - user
        - role



