mybatisGenerator:
    datasource:
        url: jdbc:mysql://35.234.41.130:3306/JS_mysql_db
        username: root
        password: Woshixxf666

    targetPackage:
        model: com.example.domain
        javaMapper: com.example.dao
        xmlMapper: com.example.dao

    targetRuntime: MyBatis3
    mapperSuffixName: mapper
    java8: false
    disableExample: true

    plugins:
        comment: false
        lombok: false
        swagger: true
        mapperAnnotation: false
        serializable: true

    tables:
        - role



