mybatisGenerator:
    datasource:
        url: jdbc:mysql://localhost:3306/test
        username: root
        password: root

    targetPackage:
        model: com.example.domain
        javaMapper: com.example.dao
        xmlMapper: com.example.dao

    targetRuntime: MyBatis3
    mapperSuffixName: mapper
    java8: false
    disableExample: true

    plugins:
        comment: true
        lombok: true
        swagger: false
        mapperAnnotation: false
        serializable: false

    tables:
        - role
        - user



